### PR TITLE
adds base XaaS Packager documentation

### PR DESCRIPTION
**Pull request by nyuuyn**
Only adds base documentation for the XaaS Packager component to reuse modelled topologies for single applications. 

No new functions or ui elements.

### CODE REVIEW

**Comment by koppor** [comment]
Thank you for the PR 🎉 

Looks good. Can you

1. Create the pull request to https://github.com/eclipse/winery? This is necessary because of the strong IP policy of Eclipse. You find more details at http://eclipse.github.io/winery/dev/ToolChain
2. Link the XaaSPackager.md from index.md? Then it will also appear at http://eclipse.github.io/winery/user/ (scroll to the bottom). Otherwise, it will be hard for the users to find it.

**Comment by nyuuyn** [comment]
@1: Should I create another pull request or can I change this?
@2: Is already added, look at the bottom of the commit :)

**Comment by koppor** [comment]
@1: Two repos -> yet another PR required. 😢 
@2: Good job, man! 🎉

**Comment by koppor** [comment]
Done at https://github.com/eclipse/winery/pull/81

Thank you!

**Comment by koppor** [comment]
Now rendered at http://eclipse.github.io/winery/user/XaaSPackager

**Pull request closed without merging**
