### PR TITLE
Feature/files

### PR DESCRIPTION
**Pull request by lharzenetter**
Use the following template for the PR title and delete this line: [WIP] Title of the thesis/work/target

- Start and end date: 
- Contributor: 
- Supervisor: 

- [ ] Ensure that you followed http://eclipse.github.io/winery/dev/ToolChain#github---prepare-pull-request.
- [ ] Branch name checked. That means, the branch name starts with `thesis/`, `fix/`, ...
- [ ] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Ensure to use auto format in **all** files
- [ ] Ensure that you appear in `NOTICE` at Copyright Holders
- [ ] Tests created for changes
- [ ] Documentation updated (if needed)
- [ ] Screenshots added (for UI changes)

### CODE REVIEW

**Comment by lharzenetter** [comment]
Also ensure that the files are referenced in the `data.xml` see https://github.com/eclipse/winery/pull/344

**Comment by lharzenetter** [comment]
@miwurster

**Comment by miwurster** [comment]
I think this PR also requires an extension to `SelfServiceModel.xsd` (similar to `ApplicationOption`) in order to have a list of files inside the `data.xml`. 

Furthermore, since we are currently using the generic `FilesResource` inside `SelfServicePortalResource`, we may have to create a facade in order to trigger the `data.xml` update on `postFile`, `putFile`, and `deleteFile` actions.

**Comment by koppor** [comment]
Typically, data.XML should be synced during export. So, no need to update
it at each write. However, seeing the other issue, the sync seems to be
broken.

Why does data XML need to list all files? Can't an intelligent CSAR
processor get a list of all contained files? Winery Repo can do that 😇

Michael Wurster <notifications@github.com> schrieb am Di., 24. Juli 2018,
14:29:

**Comment by miwurster** [comment]
Seems no one needs that anymore, right?

**Comment by miwurster** [comment]
Seems no longer relevant.

**Pull request closed without merging**
