### PR TITLE
[WIP] Feature/substitution

### PR DESCRIPTION
**Pull request by lharzenetter**
Enables the substitution of abstract Node Templates with concrete ones inheriting from the abstract one, as well as the substitution by Service Templates.

- [ ] Ensure that you followed http://eclipse.github.io/winery/dev/ToolChain#github---prepare-pull-request.
- [ ] Branch name checked. That means, the branch name starts with `thesis/`, `fix/`, ...
- [ ] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Ensure to use auto format in **all** files
- [ ] Ensure that you appear in `NOTICE` at Copyright Holders
- [ ] Tests created for changes
- [ ] Documentation updated (if needed)
- [ ] Screenshots added (for UI changes)

### CODE REVIEW

**Comment by lharzenetter** [comment]
Follow up eclipse/winery#356

**Comment by lharzenetter** [comment]
it is merged...

**Comment by nyuuyn** [comment]
screen shot 2018-10-04 at 15 48 49

Doesn't look like it was merged just closed  :octocat:

**Comment by Vogel612** [comment]
@nyuuyn the eclipse pull-request was merged. Because of the split between eclipse and OpenTOSCA's winery, pull-requests should be made against eclipse/winery. PullRequests against OpenTOSCA winery are intended as preliminary internal review targets. The changes they perform will then be merged through a separate PR against eclipse/winery, which will in turn get pulled into OpenTOSCA/winery through a simple merge.

Because eclipse pullrequests may only be a single commit, and they are based off a different commit (namely eclipse/winery@master), git (and by extension github) do not recognize they perform the same changes as the requests opened against OpenTOSCA/winery.

**Comment by lharzenetter** [comment]
This issue was fixed by the linked PR eclipse/winery#356

**Pull request closed without merging**
