### PR TITLE
Service Template Inheritance

### PR DESCRIPTION
**Pull request by nyuuyn**
- Start and end date: 2018-02-19 to 2018-02-19
- Contributor: Kálmán Képes, @nyuuyn

Adds feature to set inheritance on Service Templates

screen shot 2018-02-19 at 15 55 41

### CODE REVIEW

**Comment by nyuuyn** [comment]
Any idea why this branch merges over 200 commits ? Did I really forget to pull ?

**Comment by koppor** [comment]
You did not follow http://eclipse.github.io/winery/dev/ToolChain#steps-for-working-on-a-topic.

You branched from `origin/master`, not from `upstream/master`. I changed the base to `ustutt`.

Since yesterday, we changed the branches so that `origin/master` is `upstream/master` and if someone does not follow the ToolChain, not so much goes wrong.

**Comment by koppor** [comment]
Here, it doesn't have 200 commits. Only 4. You can merge the commits into one. Hints are given at http://eclipse.github.io/winery/dev/ToolChain#steps-for-working-on-a-topic. Then, you can cherry-pick this commits for `eclipse/master`.

**Comment by koppor** [comment]
Is https://github.com/OpenTOSCA/winery/pull/69 the successor of this PR?

**Comment by nyuuyn** [comment]
To be honest, I'm not sure how the other PR got there, maybe I messed up moving the commits to a PR for Eclipse Winery?

**Comment by koppor** [comment]
I think, this has the wrong target branch and #69 got it right.

**Pull request closed without merging**
