### PR TITLE
[WIP] feature/secure-csar

### PR DESCRIPTION
**Pull request by v-yussupov**
Adds support for modeling and enforcement of security requirements in CSARs.

What was added:
- Key management functionalities
- Extension to Node Types and Artifact Templates to support policies
- Security policies generation
- Enforcement of security policies at export time
- Verification of external and internal signatures at import time

Backend part works, but requires testing and refactoring, also it needs to be merged with the Provenance prototype as they have overlaps in CsarExporter/CsarImporter. For frontend the export/import buttons were added, policy modeling happens via xml editor. Also key management and security policy templates generation currently happens only via Winery's REST API.

- [x] Ensure that you followed http://eclipse.github.io/winery/dev/ToolChain#github---prepare-pull-request.
- [x] Branch name checked. That means, the branch name starts with `thesis/`, `fix/`, ...
- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Ensure to use auto format in **all** files
- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for UI changes)

### CODE REVIEW

**Comment by miwurster** [comment]
Hi @ghareeb-falazi, what needs to be done here in order to merge these changes?

**Comment by ghareeb-falazi** [comment]
> Hi @ghareeb-falazi, what needs to be done here in order to merge these changes?

To summarize:
- Merge master and fix conflicts
- Handle newly introduced todos
- Handle empty control flows (empty if's or else's)
- Ensure the usage of the newly introduced Encryption/ Signing Decorators when enforcing policies on the ArtifactTemplates within the `SecurityPolicyEnforcer`.
-  Ensure that hashing is not explicitly invoked before signing or checking signature (since it is already done by those operations)
- Drop the usage of deprecated modals in the Key Management UI
- Ensure that key exchange / permissioning model make sense (even from UX viewpoint)
- Write tests!
- Make CSAR export in two phases to be able to expose errors and allow the user to choose whether to continue or abort.

**Comment by miwurster** [comment]
But why is no one working on it? Either resolve the list of tasks or close it. Having this PR open forever is not a solution.

**Comment by ghareeb-falazi** [comment]
> But why is no one working on it? Either resolve the list of tasks or close it. Having this PR open forever is not a solution.

@v-yussupov  and I plan to dedicate some time for it in March, we can close it for now :)

**Pull request closed without merging**
