### PR TITLE
update third party content file

### PR DESCRIPTION
**Pull request by MCoskuner**
Use the following template for the PR title and delete this line: [WIP] Lokalitydependency of Softwarecomponents

- Start and end date: 
- Contributor: 
- Supervisor: 

- [X] Ensure that you followed http://eclipse.github.io/winery/dev/ToolChain#github---prepare-pull-request. Especially, we require **a single commit**
- [X] Ensure that the commit message is [a good commit message](https://chris.beams.io/posts/git-commit/)
- [X] Ensure to use auto format in **all** files
- [X] Change in CHANGELOG.md described
- [X] Tests created for changes
- [X] Screenshots added (for UI changes)

### CODE REVIEW

**Comment by koppor** [comment]
What do you need to change at the xlsx? Please adpat title of the PR using
the edit button on the right

Am 11.01.2018 11:43 schrieb "MCoskuner" <notifications@github.com>:

**Comment by MCoskuner** [comment]
Hi Oliver Kopp,

i didn’t have changed, the xlsx. Ive just followed the steps which are described in the ToolChain.

Best regards,
Mirac

Von: Oliver Kopp <notifications@github.com>
Antworten an: OpenTOSCA/winery <reply@reply.github.com>
Datum: Donnerstag, 11. Januar 2018 um 12:20
An: OpenTOSCA/winery <winery@noreply.github.com>
Cc: "Coskuner, Mirac" <st100147@stud.uni-stuttgart.de>, Author <author@noreply.github.com>
Betreff: Re: [OpenTOSCA/winery] update third party content file (#62)

What do you need to change at the xlsx? Please adpat title of the PR using
the edit button on the right

Am 11.01.2018 11:43 schrieb "MCoskuner" <notifications@github.com>:

**Comment by koppor** [comment]
Yeah, there was one unmerged commit from Eclipse/winery to OpenTOSCA/winery. This was the commit you had here. This rarely happens, but happened in your case.

I assume, you can just add (own) commits to your branch and they will show up here. Just continue working and we'll see how GitHub reacts.

**Comment by koppor** [comment]
The wish that you should also follow the step "Fill in the title of the Pull Request" still persists.

grafik

Your current title of the pull request is "update third party content file", but it should be of the format "[WIP] Title of the thesis/work/target".

Please push the "Edit" button:

grafik

Please also correct your description.

I marked the imporant points:

grafik

I also marked this step in http://eclipse.github.io/winery/dev/ToolChain

grafik

**Pull request merged**
